name: Playwright Tests
on:
  push:
    branches: [ playwright-tests ]
jobs:

  startServer:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build & Install
      run: dotnet build
    - name: Start server
      run: cd server && dotnet run &
    
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup Playwright
      run: dotnet tool install --global Microsoft.Playwright.CLI
    - name: Add Playwright to PATH
      run: echo "${{ github.workspace }}/.dotnet/tools" >> $GITHUB_PATH
    - name: Install Playwright
      run: playwright install --with-deps
    - name: Build & Install
      run: dotnet build
    - name: Ensure browsers are installed
      run: cd ../ShopTester.Tests && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Run your tests
      run: dotnet test